services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      - XDEBUG_MODE=${XDEBUG_MODE:-debug}
      - XDEBUG_CONFIG=client_host=host.docker.internal
      - DB_HOST=mysql
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_ENV=${APP_ENV:-dev}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_LANGUAGE=${APP_LANGUAGE:-en-US}
      - YII_COOKIE_VALIDATION_KEY=${YII_COOKIE_VALIDATION_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./application:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - yii2-network

  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./application:/var/www/html:ro
    depends_on:
      - php
    networks:
      - yii2-network

  mysql:
    image: mysql:${MYSQL_VERSION:-8.0}
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - yii2-network

volumes:
  mysql_data:

networks:
  yii2-network:
    driver: bridge